// Reads INEGI's 21a.shp (AGEB urbana boundaries, Puebla) + RESAGEBURB_21CSV20.csv (population),
// reprojects every ring from Lambert Conformal Conic (ITRF2008/GRS80) to WGS84, joins population
// by cvegeo, and writes import.sql. Adapted from ../municipal-boundaries/convert.js.
const shapefile = require("shapefile");
const proj4 = require("proj4");
const fs = require("fs");
const path = require("path");
const readline = require("readline");

const SOURCE_PROJ =
  "+proj=lcc +lat_1=17.5 +lat_2=29.5 +lat_0=12 +lon_0=-102 +x_0=2500000 +y_0=0 " +
  "+ellps=GRS80 +units=m +no_defs";
const TARGET_PROJ = "+proj=longlat +datum=WGS84 +no_defs";
const reproject = proj4(SOURCE_PROJ, TARGET_PROJ);

function reprojectRing(ring) {
  return ring.map(([x, y]) => {
    const [lng, lat] = reproject.forward([x, y]);
    return `${lng.toFixed(7)} ${lat.toFixed(7)}`;
  });
}

function coordsToWkt(geometry) {
  if (geometry.type === "Polygon") {
    const rings = geometry.coordinates.map((ring) => `(${reprojectRing(ring).join(", ")})`);
    return `POLYGON(${rings.join(", ")})`;
  }
  if (geometry.type === "MultiPolygon") {
    const polys = geometry.coordinates.map(
      (poly) => `(${poly.map((ring) => `(${reprojectRing(ring).join(", ")})`).join(", ")})`
    );
    return `MULTIPOLYGON(${polys.join(", ")})`;
  }
  throw new Error(`Unexpected geometry type: ${geometry.type}`);
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Simple CSV line splitter — the source file has no quoted/embedded-comma fields (verified: every
// field is a bare number or a short unquoted label), so a plain split is safe and avoids pulling
// in a CSV parsing dependency for a one-off script.
function parseCsvLine(line) {
  return line.split(",");
}

async function loadPopulationByCvegeo(csvPath) {
  const byCvegeo = new Map();
  // Strip the raw UTF-8 BOM bytes (EF BB BF) from the buffer BEFORE decoding as latin1 — decoding
  // them as latin1 first turns the BOM into 3 garbage characters ("ï»¿") prepended to the first
  // header name instead of the single U+FEFF a post-decode regex would catch, silently breaking
  // every row's ENTIDAD lookup (and therefore every cvegeo built from it).
  let buf = fs.readFileSync(csvPath);
  if (buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf) buf = buf.subarray(3);
  const rl = readline.createInterface({ input: require("stream").Readable.from(buf.toString("latin1")) });
  let header = null;
  for await (const line of rl) {
    const fields = parseCsvLine(line);
    if (!header) {
      header = fields;
      continue;
    }
    const row = Object.fromEntries(header.map((h, i) => [h, fields[i]]));
    if (row.NOM_LOC !== "Total AGEB urbana") continue;
    const cvegeo = `${row.ENTIDAD}${row.MUN}${row.LOC}${row.AGEB}`;
    const pobtot = parseInt(row.POBTOT, 10);
    byCvegeo.set(cvegeo, Number.isFinite(pobtot) ? pobtot : null);
  }
  return byCvegeo;
}

async function main() {
  const shpPath = path.join(__dirname, "21a.shp");
  const dbfPath = path.join(__dirname, "21a.dbf");
  const csvPath = path.join(__dirname, "RESAGEBURB_21CSV20.csv");

  const population = await loadPopulationByCvegeo(csvPath);
  console.log(`Loaded population for ${population.size} AGEBs from the census CSV.`);

  const source = await shapefile.open(shpPath, dbfPath, { encoding: "latin1" });
  const rows = [];
  const skipped = [];
  let result = await source.read();
  while (!result.done) {
    const { properties, geometry } = result.value;
    const cvegeo = properties.CVEGEO;
    const pop = population.get(cvegeo);
    if (pop === undefined || pop === null) {
      skipped.push(cvegeo);
    } else {
      rows.push({ cvegeo, population: pop, wkt: coordsToWkt(geometry) });
    }
    result = await source.read();
  }

  console.log(`Read ${rows.length + skipped.length} AGEB polygons; ${rows.length} matched a population row, ${skipped.length} skipped (no census match).`);
  if (skipped.length > 0) {
    console.log("Skipped cvegeos (no fabricated population value written for these):", skipped.join(", "));
  }

  const outPath = path.join(__dirname, "import.sql");
  const lines = [];
  lines.push("-- Generated by convert.js — see README.md. Do not hand-edit; regenerate instead.");
  lines.push("BEGIN;");
  lines.push("CREATE TEMP TABLE staging_ageb_boundaries (");
  lines.push("  cvegeo varchar(13) PRIMARY KEY,");
  lines.push("  population integer NOT NULL,");
  lines.push("  boundary geometry NOT NULL");
  lines.push(");");
  lines.push("");

  for (const row of rows) {
    lines.push(
      `INSERT INTO staging_ageb_boundaries (cvegeo, population, boundary) VALUES (` +
        `${sqlString(row.cvegeo)}, ${row.population}, ` +
        `ST_SetSRID(ST_GeomFromText(${sqlString(row.wkt)}), 4326));`
    );
  }

  lines.push("");
  lines.push("-- area_sq_km computed here (geography cast, PostGIS's geodesic area), not in JS —");
  lines.push("-- avoids hand-rolling spherical-polygon math for a one-off import.");
  lines.push("-- Idempotent: replace on cvegeo conflict rather than accumulating duplicates. census_year");
  lines.push("-- is fixed 2020 (this entire import is one census edition); socioeconomic columns are");
  lines.push("-- deliberately left untouched here — that's what ../ageb-socioeconomic/import.sql owns,");
  lines.push("-- and it must run AFTER this script so its base rows already exist to UPDATE.");
  lines.push("INSERT INTO ageb_populations (cvegeo, population, area_sq_km, boundary, census_year)");
  lines.push("SELECT cvegeo, population, ST_Area(boundary::geography) / 1000000.0, boundary, 2020");
  lines.push("FROM staging_ageb_boundaries");
  lines.push("ON CONFLICT (cvegeo) DO UPDATE SET");
  lines.push("  population = EXCLUDED.population, area_sq_km = EXCLUDED.area_sq_km,");
  lines.push("  boundary = EXCLUDED.boundary, census_year = EXCLUDED.census_year;");
  lines.push("");
  lines.push("SELECT count(*) AS imported_count FROM ageb_populations;");
  lines.push("COMMIT;");

  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
