// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealEstate.Api.Data;

#nullable disable

namespace RealEstate.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922133707_AddFraccionamientos")]
    partial class AddFraccionamientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.AgebPopulation", b =>
                {
                    b.Property<string>("Cvegeo")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("cvegeo");

                    b.Property<double>("AreaSqKm")
                        .HasColumnType("double precision")
                        .HasColumnName("area_sq_km");

                    b.Property<double?>("AvgOccupantsPerHome")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_occupants_per_home");

                    b.Property<double?>("AvgSchoolingYears")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_schooling_years");

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("boundary");

                    b.Property<int>("CensusYear")
                        .HasColumnType("integer")
                        .HasColumnName("census_year");

                    b.Property<int?>("EstimatedSocioeconomicLevel")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_socioeconomic_level");

                    b.Property<double?>("PctHomesWithCar")
                        .HasColumnType("double precision")
                        .HasColumnName("pct_homes_with_car");

                    b.Property<double?>("PctHomesWithComputer")
                        .HasColumnType("double precision")
                        .HasColumnName("pct_homes_with_computer");

                    b.Property<double?>("PctHomesWithInternet")
                        .HasColumnType("double precision")
                        .HasColumnName("pct_homes_with_internet");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<double?>("SocioeconomicScore")
                        .HasColumnType("double precision")
                        .HasColumnName("socioeconomic_score");

                    b.HasKey("Cvegeo")
                        .HasName("pk_ageb_populations");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_ageb_populations_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.ToTable("ageb_populations", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_error_logs");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_error_logs_occurred_at");

                    b.HasIndex("Resolved")
                        .HasDatabaseName("ix_error_logs_resolved");

                    b.HasIndex("Source", "Severity", "Section")
                        .HasDatabaseName("ix_error_logs_source_severity_section");

                    b.ToTable("error_logs", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_favorites");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_favorites_listing_id");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("ix_favorites_user_id_listing_id");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Fraccionamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmenitiesJson")
                        .HasColumnType("text")
                        .HasColumnName("amenities_json");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DeveloperName")
                        .HasColumnType("text")
                        .HasColumnName("developer_name");

                    b.Property<DateTime>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MasterPlanImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("master_plan_image_url");

                    b.Property<Guid?>("MergedIntoId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Stage")
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_fraccionamientos");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fraccionamientos_status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_fraccionamientos_latitude_longitude");

                    b.ToTable("fraccionamientos", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.FraccionamientoSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("FraccionamientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fraccionamiento_id");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_data_json");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_fraccionamiento_sources");

                    b.HasIndex("FraccionamientoId")
                        .HasDatabaseName("ix_fraccionamiento_sources_fraccionamiento_id");

                    b.ToTable("fraccionamiento_sources", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FundingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("funding_method");

                    b.Property<bool?>("HasAgent")
                        .HasColumnType("boolean")
                        .HasColumnName("has_agent");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_email");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderPhone")
                        .HasColumnType("text")
                        .HasColumnName("sender_phone");

                    b.Property<int?>("Timeline")
                        .HasColumnType("integer")
                        .HasColumnName("timeline");

                    b.HasKey("Id")
                        .HasName("pk_inquiries");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_inquiries_listing_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_inquiries_sender_id");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<int>("AreaSqFt")
                        .HasColumnType("integer")
                        .HasColumnName("area_sq_ft");

                    b.Property<decimal>("Bathrooms")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("bathrooms");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("bedrooms");

                    b.Property<decimal?>("CadastralValue")
                        .HasColumnType("numeric")
                        .HasColumnName("cadastral_value");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<decimal?>("CosCoefficient")
                        .HasColumnType("numeric")
                        .HasColumnName("cos_coefficient");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("MXN")
                        .HasColumnName("currency");

                    b.Property<decimal?>("CusCoefficient")
                        .HasColumnType("numeric")
                        .HasColumnName("cus_coefficient");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer")
                        .HasColumnName("floors");

                    b.Property<Guid?>("FraccionamientoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fraccionamiento_id");

                    b.Property<decimal?>("FrontageDepthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("frontage_depth_meters");

                    b.Property<decimal?>("FrontageWidthMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("frontage_width_meters");

                    b.Property<decimal?>("GardenSizeSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("garden_size_sqm");

                    b.Property<bool?>("HasDrainage")
                        .HasColumnType("boolean")
                        .HasColumnName("has_drainage");

                    b.Property<bool?>("HasElectricity")
                        .HasColumnType("boolean")
                        .HasColumnName("has_electricity");

                    b.Property<bool>("HasHeatingCooling")
                        .HasColumnType("boolean")
                        .HasColumnName("has_heating_cooling");

                    b.Property<bool?>("HasNearbyUTurn")
                        .HasColumnType("boolean")
                        .HasColumnName("has_nearby_u_turn");

                    b.Property<bool?>("HasPotableWater")
                        .HasColumnType("boolean")
                        .HasColumnName("has_potable_water");

                    b.Property<bool?>("HasPropertyTaxDebt")
                        .HasColumnType("boolean")
                        .HasColumnName("has_property_tax_debt");

                    b.Property<bool?>("HasTelecomService")
                        .HasColumnType("boolean")
                        .HasColumnName("has_telecom_service");

                    b.Property<bool?>("HasThreePhaseElectricity")
                        .HasColumnType("boolean")
                        .HasColumnName("has_three_phase_electricity");

                    b.Property<bool?>("HasVehicleAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("has_vehicle_access");

                    b.Property<bool?>("HasWaterDebt")
                        .HasColumnType("boolean")
                        .HasColumnName("has_water_debt");

                    b.Property<decimal?>("HoaFee")
                        .HasColumnType("numeric")
                        .HasColumnName("hoa_fee");

                    b.Property<bool?>("IsCornerLot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_corner_lot");

                    b.Property<bool?>("IsFloodRiskZone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flood_risk_zone");

                    b.Property<bool?>("IsFreeOfLiens")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free_of_liens");

                    b.Property<int?>("LandTenure")
                        .HasColumnType("integer")
                        .HasColumnName("land_tenure");

                    b.Property<string>("LandUseZoning")
                        .HasColumnType("text")
                        .HasColumnName("land_use_zoning");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("LotShape")
                        .HasColumnType("integer")
                        .HasColumnName("lot_shape");

                    b.Property<decimal?>("LotSizeSqm")
                        .HasColumnType("numeric")
                        .HasColumnName("lot_size_sqm");

                    b.Property<decimal?>("MaxHeightMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("max_height_meters");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("integer")
                        .HasColumnName("parking_spaces");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price");

                    b.Property<int?>("PrimaryVialidadType")
                        .HasColumnType("integer")
                        .HasColumnName("primary_vialidad_type");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("StreetFrontageCount")
                        .HasColumnType("integer")
                        .HasColumnName("street_frontage_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Topography")
                        .HasColumnType("integer")
                        .HasColumnName("topography");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoTourUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_tour_url");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer")
                        .HasColumnName("year_built");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_listings_city");

                    b.HasIndex("FraccionamientoId")
                        .HasDatabaseName("ix_listings_fraccionamiento_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_listings_owner_id");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_listings_latitude_longitude");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_listing_images");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_images_listing_id");

                    b.ToTable("listing_images", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ListingPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("MXN")
                        .HasColumnName("currency");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_listing_price_histories");

                    b.HasIndex("ListingId", "RecordedAt")
                        .HasDatabaseName("ix_listing_price_histories_listing_id_recorded_at");

                    b.ToTable("listing_price_histories", (string)null);
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ListingType")
                        .HasColumnType("integer")
                        .HasColumnName("listing_type");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("max_price");

                    b.Property<int?>("MinBathrooms")
                        .HasColumnType("integer")
                        .HasColumnName("min_bathrooms");

                    b.Property<int?>("MinBedrooms")
                        .HasColumnType("integer")
                        .HasColumnName("min_bedrooms");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("min_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_searches");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_searches_user_id");

                    b.ToTable("saved_searches", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Favorite", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Listing", "Listing")
                        .WithMany("Favorites")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_listings_listing_id");

                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.FraccionamientoSource", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Fraccionamiento", "Fraccionamiento")
                        .WithMany("Sources")
                        .HasForeignKey("FraccionamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fraccionamiento_sources_fraccionamientos_fraccionamiento_id");

                    b.Navigation("Fraccionamiento");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Inquiry", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Listing", "Listing")
                        .WithMany("Inquiries")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_listings_listing_id");

                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inquiries_users_sender_id");

                    b.Navigation("Listing");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Listing", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Fraccionamiento", "Fraccionamiento")
                        .WithMany("Listings")
                        .HasForeignKey("FraccionamientoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_listings_fraccionamientos_fraccionamiento_id");

                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", "Owner")
                        .WithMany("Listings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_owner_id");

                    b.Navigation("Fraccionamiento");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ListingImage", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_images_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ListingPriceHistory", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.Listing", "Listing")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_price_histories_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.SavedSearch", b =>
                {
                    b.HasOne("RealEstate.Api.Models.Entities.ApplicationUser", "User")
                        .WithMany("SavedSearches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_searches_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Listings");

                    b.Navigation("SavedSearches");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Fraccionamiento", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("RealEstate.Api.Models.Entities.Listing", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Inquiries");

                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
